language: node_js
node_js:
- node
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
deploy:
  provider: npm
  email: dev@dasilvacamposanis.fr
  api_key:
    secure: dRSFP0kgfpY2q1U7QXfmSN4CKejSVqcndCcHZv2c185VupUmRT6ANDiDztGeLytwP+b1ixKeOLJKyEj/ltsDMaoQr9r+qTeU6ftYwGWgwmQnONHNpxAKIGpOh69a7gF2OgCl45UsX0eJIqkA52bpu81hqfQCz4GJJUJkaQoSjyCZmpBfQ64+kPQpFCHUQ5AKppJi/O+wvbn8A4/DNr/kYQO+pypwj7ZuJVrZUgwx625LGq2dbYCG1WFAGgOsPJKIR5r7Ms3Qq6jUfQmziy59pvLzpO2kT8CC9p4i2bP1m6VyzsgCK9vL1pG7sLu0lOcnlEVA68JKMWuFDtLBaNYvCkRBzDHylv153b+zG8dG+KjP9oukUKFaVGsDwb8ugh4DdhvbPu5ijYl0t3ZpYB2Pi1wnH5ExFcFpHfs2+KCRyZBD62irLf+XCIcr7jrgtB3YcTMEkYz8IQIvAwqDjgngZqxYi2BX/HQraHeNUkyLgDcFNBOcu0KGDcYA+di/cfbXFFY7p/DULe9r1PXxju2HnKBSXTSJpGXBME507Uk3MLypnzcddBWau3Xi74/r2+sRfNs7fNiIdGz1Zha4ySxTgmb95ERufpfibVJmyspIwKhRCRgBI3auQRJftuVhpwoZ0nAo3qibR/ZpJCuD20SvW+BMXIlu3vdImeVAawrfOQI=
  on:
    tags: true
    repo: anis-campos/redux-reactstrap-modal
